language: r
pandoc_version: 1.19.2.1
sudo: required
# cache:
#   packages: true
#   directories:
#   - manuscript/cache

cache: packages
addons:
  apt:
    packages:
      - libgit2-dev

apt_pacakges:
  - r-cran-java
  - libgsl-dev
  - libproj-dev
  - libgdal-dev
  - open-cobol

before_install:
  - sudo $(which R) CMD javareconf
  - Rscript -e 'if (!requireNamespace("BiocManager", quietly = TRUE)) { install.packages("BiocManager"); BiocManager::install("Biobase")}'


before_script:
- chmod +x ./_build_and_deploy.sh
- git config --global user.email "yushiro@hacarus.com"
- git config --global user.name "yushiro"
script: ./_build_and_deploy.sh
env:
  global:
  # - secure: jmo/WiDp6XfW5zU7e9yZuktt74+5WlzqKtXv3Tq14LUdDNuQfopPAvobjh6/ZVIcxA+lsfGt6G2lDMsKBsKuVOK0rrk99WmAt0UWEvS16ftoldFs3U3xHZI9YXmd1iBT5h4b5GNL25woGHfxyHw87dQkacatAbXH7b8D24ALRNvx1UAGVW4Dz/D52xvgL6Lncu296SrGA9PqXmiHuq679p7j7V90+z5KK9XxI1PcYNRKhMdtQkswa4132GM42tBQ8OoU4v2aWBgBEtSO8J6KXO/B1j184c0aSU2qoooxFCN0ZeR+ECs418wDj7wj98VfQDFCUOCteVmLSvLHgct2t70F5bNPbn+7PD+cwz4HPEy7zJffHxjKepsiLZEWUkGoQ6cSYEUUOicAOL0lrQtLxA14Yz/Y569Iq6/TrxL+FDYXBmJkwZ5gBffEbmGfmubkUZLNBfh+n65VYl71tGWM9e8tYBPLq1G0c+2cbN4E9H/A3wo7sP4JjKHmUVvZjqAOfxuuFpXua6wPSa6AyuuvjKfDzJOYjro6CWO4KYjUZ6qZ9DEt+xVrv39KMUviVTZPnUzc8kmz0zFDFnvJeOo/AGZ8ackDK6C3UJmpCAUxkdqFywHcAdl5vhoF4o5kk5Ucsa9Yn+SfNAe3jOicEV1M5U8yZ4vr/xUJTS0E/opkQMc=
  - secure: MUZEYj5vhxNUAttzVOuBuxhiwgCpDU3qEVLE9jSuxM4GcWG12ajJgWxFa3vKMttPsXzx8ryVxDO4r497nfDVcK79BY5ugs5XTKL5xJ6RaMhWvkQ5Pj87RMR3+KV5Rtn7ub+RWqmL6YDVDfvIl1Hn0Mz1y8cKPcR3YLVCynzw6KPttWDoRrcKTublH1UZ3ulIi1edP/rXo03rgZtRh8JAATE23H0cmgJ6inKDL8yIc0U3sGIz42dNbf0NXtTl7s/rivx4wi+ZCVm5ft4+FDKuNiPzkTfAD5MM8fRHMLNi+i0Zk7RCP3TNCFrsD1r8i2diy0iAvLrzsBYtdx36D88vu0ES5PCFQsy8DaTT9NvIQPOW11zZ9qFs639cXrmj/5uDNjstotju2oLgaOyPl+5UTtP+cuLIW3i28Edo8MQTpHD58e2eiKeZrqw9ddz69VbSkq0CpU1v0IpyOb4dYXc3YohCoojQB5LTzC0sNvMrUKuPb2UDBvWPOdILrxsb2tJISDYrEFZ566g8YwltbOH2b3XRgutHfmh2OS+J3iWimq0bL8fyx40w8c3YH0iIKB+0zsXuD1Rd41Kn18x199TkZb1ESDtxo4WKB+tPY4sBTUmo0cNjIsHjJnTmxskU4DVDtCpNH+Jmhd8ng81a5Q5hfd846lEMBhafyXuFkxc2OfU=

